openapi: 3.0.3
info:
  title: Documentation for Sportify 3.0
  version: 1.0.0
servers:
  - url: https://htplvd3xti.execute-api.us-east-1.amazonaws.com/dev
tags:
  - name: product
    description: Everything about sport products
paths:
  /products:
    get:
      tags:
        - product
      summary: List of products
      description: Get list of all products in the store
      operationId: getProductsList
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetProductsResponse'          
  /products/{productId}:
    get:
      tags:
        - product
      summary: Find pruduct by ID
      description: Returns a single product
      operationId: getProductById
      parameters:
        - name: productId
          in: path
          description: ID of product to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'          
        '404':
          description: Product not found
components:
  schemas:
    GetProductsResponse:
        type: array
        items: 
          $ref: '#/components/schemas/Product'
    Product:
      type: object
      properties:
        id:
          type: string
          example: 7567ec4b-b10c-48c5-9345-fc73c48a80aa
        title:
          type: string
          example: ball
        description:
          type: string
          example: Description of product
        price:
          type: number
          example: 50.5
        count:
          type: integer
          example: 3
        